[workspace]
members = [
    "src/*"]

[workspace.package]
version = "0.1.0"
authors = ["restate.dev"]
edition = "2021"
rust-version = "1.66"
license = "BUSL-1.1"
repository = "https://github.com/restatedev/restate"

[workspace.dependencies]
bytes = "1.3"
clap = { version = "4.0", features = ["derive", "env"] }
serde = "1.0"
thiserror = "1.0"
tracing = "0.1"
tokio = "1.23"

# Own crates
config = { path = "src/config" }
common = { path = "src/common" }
meta = { path = "src/meta" }
protocol = { path = "src/protocol" }
storage = { path = "src/storage" }
tracing-instrumentation = { path = "src/tracing-instrumentation" }
worker = { path = "src/worker" }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1

