[package]
name = "restate-schema"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
restate-errors = { workspace = true }
restate-schema-api = { workspace = true, features = ["component", "deployment", "subscription", "invocation_target", "serde"] }
restate-types = { workspace = true }
restate-service-protocol = { workspace = true, features = ["discovery"] }

arc-swap = { workspace = true }
bytes = { workspace = true }
codederror = { workspace = true }
http = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
restate-schema-api = { workspace = true, features = ["mocks"] }
restate-test-util = { workspace = true }

googletest = { workspace = true }
test-log = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
