[package]
name = "storage_api"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
common = { workspace = true}
bytes = { workspace = true }
storage_proto = { workspace = true}
futures-util = {workspace = true}
thiserror = { workspace = true }