[package]
name = "storage_proto"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
bytes = { workspace = true }
bytes-utils = { workspace = true, optional = true }
prost = { workspace = true }
prost-types = { workspace = true }
thiserror = { workspace = true, optional = true }

[build-dependencies]
prost-build = { workspace = true }
