[package]
name = "restate"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
drain = { workspace = true }
futures-util = { workspace = true }
humantime = "2.1.0"
meta = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-instrumentation = { workspace = true }
